"""simplify_drops

Revision ID: 3f761f4ec2d3
Revises: 20260703_0005
Create Date: 2026-07-06 21:46:33.825443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f761f4ec2d3'
down_revision: Union[str, None] = '20260703_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('drops', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('drops', 'sport_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('drops_sport_id_fkey', 'drops', type_='foreignkey')
    op.create_foreign_key(None, 'drops', 'sports', ['sport_id'], ['id'], ondelete='SET NULL')
    op.alter_column('match_stats', 'sport',
               existing_type=postgresql.ENUM('football', 'cricket', 'basketball', name='sport_enum'),
               nullable=True)
    op.alter_column('match_stats', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_player_profiles_sport_id'), 'player_profiles', ['sport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_profiles_sport_id'), table_name='player_profiles')
    op.alter_column('match_stats', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('match_stats', 'sport',
               existing_type=postgresql.ENUM('football', 'cricket', 'basketball', name='sport_enum'),
               nullable=False)
    op.drop_constraint(None, 'drops', type_='foreignkey')
    op.create_foreign_key('drops_sport_id_fkey', 'drops', 'sports', ['sport_id'], ['id'], ondelete='CASCADE')
    op.alter_column('drops', 'sport_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('drops', 'location')
    op.drop_column('drops', 'audience')
    # ### end Alembic commands ###
