"""add_login_attempts

Revision ID: 7bda983d7389
Revises: 20260707_0006
Create Date: 2026-07-07 13:54:27.108923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bda983d7389'
down_revision: Union[str, None] = '20260707_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('identifier', postgresql.CITEXT(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=True)
    op.add_column('email_otps', sa.Column('purpose', sa.String(), nullable=False))
    op.drop_constraint('email_otps_user_id_key', 'email_otps', type_='unique')
    op.create_unique_constraint('uq_email_otps_user_purpose', 'email_otps', ['user_id', 'purpose'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_otps_user_purpose', 'email_otps', type_='unique')
    op.create_unique_constraint('email_otps_user_id_key', 'email_otps', ['user_id'])
    op.drop_column('email_otps', 'purpose')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
